### ISSUE TITLE
Template Strings Not Supported

### ISSUE THREAD

**Issue by ElectricCoffee** [thomblake/js3-mode#110] opened 2015-09-29 13:38 UTC
[Template Strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) are a neat feature in JS that lets you interpolate data into your strings using back-ticks (`` ` ``).

JS3 will say `` ` `` is an illegal character and render the string incorrectly

**Comment by thomblake** [comment] 2015-09-29 17:47
Yeah in general js3-mode's version of Rhino doesn't support new es6 syntax.

**Comment by thomblake** [comment] 2015-09-29 17:51
Actually closing this as duplicate of #107

**Closed by thomblake** 2015-09-29 17:51 UTC
Labels: Feature, patch-welcome
